# Generated by Django 3.2.18 on 2024-03-05 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted', models.BooleanField(default=False, verbose_name='是否已提交')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_exams', to='exam.exam', verbose_name='试卷')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_exams', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
        ),
        migrations.CreateModel(
            name='UserScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, verbose_name='得分')),
                ('user_exam', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='exam.userexam', verbose_name='用户试卷')),
            ],
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exam.choice', verbose_name='选择')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exam.question', verbose_name='问题')),
                ('user_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exam.userexam', verbose_name='用户试卷')),
            ],
        ),
    ]
