# Generated by Django 3.2.5 on 2024-07-05 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_auto_20240705_0936'),
    ]

    operations = [
        migrations.CreateModel(
            name='FillInBlankAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_answer', models.CharField(max_length=200, verbose_name='正确答案')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fill_in_blank_answers', to='exam.question', verbose_name='题目')),
            ],
        ),
    ]
