# Generated by Django 3.2.5 on 2024-07-05 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_fillinblankanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='fillinblankanswer',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='是否正确答案'),
        ),
    ]
