# Generated by Django 3.2.5 on 2024-07-05 04:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exam', '0006_fillinblankanswer_is_correct'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncorrectAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incorrect_answer', models.TextField(verbose_name='错误答案')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incorrect_answers', to='exam.question', verbose_name='问题')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incorrect_answers', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
        ),
    ]
